services:
  payload:
    command: sh -c "yarn install && yarn build && yarn serve"  # Production build
    volumes:
      - node_modules:/home/node/app/node_modules
    restart: unless-stopped

  mongo:
    # Optionally, remove port exposure for MongoDB
    ports: []
    restart: unless-stopped
