version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/home/node/app  # Only in dev, will override for production
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    depends_on:
      - mongo
    env_file:
      - .env  # Override this in production as needed

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:


# For development run
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

# For production run
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

# Script migracion HumHub
# docker-compose run --rm payload yarn migrate:humhub
# docker-compose run --rm payload yarn migrate:humhub 11 #arranca desde pagina 11 de la api
# Script migracion nativa Payload
# docker-compose run --rm payload yarn payload migrate

# Entrar a mongo shell
# docker exec -it {my_mongo_container} mongosh

# Script backup db
# ./backup_db.sh

# Script restore db
# ./restore_db.sh